#! /bin/bash

#mkdir -p saved_models

CUDA_VISIBLE_DEVICES=2 python3 train.py  --num_epochs=200 --word_dim=50
# python train.py  --num_epochs=200 --word_dim=50 --test
# src/scorer.pl data/results.txt data/test_keys.txt 

# python train.py  --num_epochs=200 --word_dim=300
# python train.py  --num_epochs=200 --word_dim=300 --test
# perl scorer.pl data/results.txt data/test_keys.txt